import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
const P=new URL('../', import.meta.url).pathname;
const db = new PGlite();
const ok=(c,m)=>{ console.log((c?'PASS ':'FAIL ')+m); if(!c) process.exitCode=1; };
await db.exec(`
create role anon nologin; create role authenticated nologin;
create schema auth;
create table auth.users(id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
grant usage on schema auth to anon, authenticated; grant execute on function auth.uid() to anon, authenticated;
grant usage on schema public to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;
`);
await db.exec(fs.readFileSync(P+'migrations/20261008120000_init.sql','utf8'));
await db.exec(fs.readFileSync(P+'seed.sql','utf8'));
const cnt=async t=>(await db.query(`select count(*)::int n from public.${t}`)).rows[0].n;
ok(await cnt('path_nodes')===48,'48 path nodes'); ok(await cnt('phrases')===64,'64 phrases'); ok(await cnt('dialog_lines')===48,'48 dialog lines');
const A=(await db.query(`insert into auth.users(email,raw_user_meta_data) values('a@x.ge','{"display_name":"ანა","daily_goal_xp":"20","self_level":"0"}') returning id`)).rows[0].id;
const B=(await db.query(`insert into auth.users(email,raw_user_meta_data) values('b@x.ge','{"display_name":"დათო","daily_goal_xp":"99"}') returning id`)).rows[0].id;
ok((await db.query(`select daily_goal_xp from profiles where id=$1`,[B])).rows[0].daily_goal_xp===20,'invalid goal falls back to 20');
const as=async(uid,sql,params=[])=>{ await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${uid}',false);`); try{ return await db.query(sql,params); } finally { await db.exec(`reset role;`);} };
const tryAs=async(...a)=>{ try{ return {r:await as(...a)}; }catch(e){ return {e:e.message}; } };
const ans=(arr)=>JSON.stringify(arr.map(([t,it,id,c])=>({exercise_type:t,item_type:it,item_id:id,correct:c})));
const perfect=ans([['word','vocab','u1.v1',true],['build','phrase','u1.p2',true]]);
let r=await as(A,`select complete_session('lesson','u1.n1',null,'{u1}',$1) j`,[perfect]); let j=r.rows[0].j;
ok(j.xp_earned===15 && j.perfect,'first perfect lesson = 15 XP'); ok(j.quest_gems===15,'perfect quest paid on first perfect lesson'); ok(j.stats.streak_current===1,'streak starts at 1');
r=await tryAs(A,`select complete_session('lesson','u1.n4',null,'{u1}',$1)`,[perfect]); ok(r.e&&/locked/.test(r.e),'skipping ahead is refused');
r=await tryAs(A,`select open_chest('u1.n3')`); ok(r.e&&/locked/.test(r.e),'chest locked before lesson 2');
const withMiss=ans([['build','phrase','u1.p5',false],['build','phrase','u1.p5',true],['type','phrase','u1.p6',false],['word','vocab','u1.v2',true]]);
r=await as(A,`select complete_session('lesson','u1.n2',null,'{u1}',$1) j`,[withMiss]); j=r.rows[0].j;
ok(j.xp_earned===10 && !j.perfect,'lesson with mistakes = 10 XP');
let m=(await as(A,`select item_id, miss_count from item_mistakes order by item_id`)).rows; ok(m.length===1 && m[0].item_id==='u1.p6','only last-wrong item remembered');
ok(j.quest_gems===20,'XP and 2-lessons quests paid once goal reached');
r=await as(A,`select open_chest('u1.n3') j`); ok(r.rows[0].j.gems===120+35+20,'chest gives 20 gems');
r=await tryAs(A,`select open_chest('u1.n3')`); ok(r.e&&/already/.test(r.e),'chest only once');
r=await as(A,`select complete_session('lesson','u1.n1',null,'{u1}',$1) j`,[ans([['word','vocab','u1.v1',false],['word','vocab','u1.v1',true]])]); ok(r.rows[0].j.xp_earned===5,'replay = 5 XP');
await as(A,`select lose_heart()`); await as(A,`select lose_heart()`); r=await as(A,`select hearts from user_stats`); ok(r.rows[0].hearts===3,'lose_heart x2 -> 3');
r=await as(A,`select complete_session('practice',null,'mistakes','{u1}',$1) j`,[ans([['type','phrase','u1.p6',true]])]); j=r.rows[0].j;
ok(j.healed && j.stats.hearts===4 && j.xp_earned===5,'practice heals a heart, 5 XP'); m=(await as(A,`select * from item_mistakes`)).rows; ok(m.length===0,'correct answer clears mistake');
for(let i=0;i<4;i++) await as(A,`select lose_heart()`);
r=await tryAs(A,`select complete_session('lesson','u1.n4',null,'{u1}',$1)`,[perfect]); ok(r.e&&/hearts/.test(r.e),'no hearts blocks lessons');
r=await as(A,`select refill_hearts() j`); ok(r.rows[0].j.hearts===5,'refill hearts with gems');
// RLS
r=await as(B,`select count(*)::int n from user_stats`); ok(r.rows[0].n===1,'B sees only own stats');
r=await as(B,`select count(*)::int n from learning_sessions`); ok(r.rows[0].n===0,'B cannot see A sessions');
r=await tryAs(A,`update user_stats set gems=99999`); ok(r.e || (await db.query(`select gems from user_stats where user_id=$1`,[A])).rows[0].gems<9999,'client cannot edit stats');
r=await tryAs(A,`update profiles set display_name='ანა ბ.', daily_goal_xp=30 where id=auth.uid()`); ok(!r.e,'profile settings editable');
r=await tryAs(A,`update profiles set created_at=now()`); ok(!!r.e,'other profile columns locked');
r=await tryAs(B,`update profiles set display_name='hacked' where id='${A}'`); ok((await db.query(`select display_name from profiles where id=$1`,[A])).rows[0].display_name==='ანა ბ.','B cannot edit A profile');
await db.exec(`set role anon;`); let e=null; try{ await db.query(`select complete_session('practice',null,'quick','{u1}','[{"correct":true}]')`);}catch(x){e=x.message} await db.exec('reset role'); ok(!!e,'anon cannot call game functions');
await db.exec(`set role anon;`); r=await db.query(`select count(*)::int n from units`); await db.exec('reset role'); ok(r.rows[0].n===8,'content readable without login');
r=await as(B,`select complete_session('practice',null,'quick','{u1}',$1) j`,[perfect]);
r=await as(B,`select * from weekly_leaderboard(10)`); ok(r.rows.length===2 && r.rows[0].display_name==='ანა ბ.' && r.rows[1].is_me,'leaderboard ranks both, marks me');
r=await tryAs(A,`select complete_session('practice',null,'quick','{u1}','[]')`); ok(!!r.e,'empty answers rejected');
await as(B,`select delete_my_account()`); ok((await db.query(`select count(*)::int n from profiles where id=$1`,[B])).rows[0].n===0 && (await db.query(`select count(*)::int n from learning_sessions where user_id=$1`,[B])).rows[0].n===0,'delete account cascades');
await as(A,`select reset_my_progress()`); r=await as(A,`select xp_total, gems from user_stats`); ok(r.rows[0].xp_total===0 && r.rows[0].gems===120,'reset progress');
