// Course content for Leap English. Edit here, then run `npm run seed:generate` to refresh supabase/seed.sql.
import type { Character, CharacterId, Section, Unit } from './types';

export const CHARACTERS: Record<CharacterId, Character> = {
  nino: { id: 'nino', name: "ნინო", isGeorgian: true, bio: "სტუდენტი თბილისიდან. ინგლისურს შენთან ერთად სწავლობს.", look: {"skin": "#F1C7A1", "hair": "#4A2C1A", "style": "long", "shirt": "#E8536B", "bg": "#3A1F2A"} },
  giorgi: { id: 'giorgi', name: "გიორგი", isGeorgian: true, bio: "ნინოს ძმა, პროგრამისტი. ბევრს მოგზაურობს.", look: {"skin": "#E3B48A", "hair": "#21160F", "style": "beard", "shirt": "#3B7DD8", "bg": "#17263D"} },
  tamar: { id: 'tamar', name: "თამარი", isGeorgian: true, bio: "მასწავლებელი ქუთაისიდან, კონფერენციებზე დადის.", look: {"skin": "#EDC09A", "hair": "#2A1A12", "style": "bun", "shirt": "#2BAE8E", "bg": "#14302A"} },
  luka: { id: 'luka', name: "ლუკა", isGeorgian: true, bio: "ბათუმელი ბიჭი, პირველად ჩავიდა ლონდონში.", look: {"skin": "#E9BB91", "hair": "#7A4A22", "style": "short", "shirt": "#F2994A", "bg": "#33220F"} },
  mariam: { id: 'mariam', name: "მარიამი", isGeorgian: true, bio: "დიზაინერი, ლონდონში ცხოვრობს.", look: {"skin": "#D9A47C", "hair": "#3A2418", "style": "curly", "shirt": "#9B6BDE", "bg": "#2A1F3D"} },
  tom: { id: 'tom', name: "Tom", isGeorgian: false, bio: "ახალი მეგობარი ლონდონიდან", look: {"skin": "#F4D0B5", "hair": "#C98A3A", "style": "short", "shirt": "#4C6EF5", "bg": "#1C2340"} },
  emma: { id: 'emma', name: "Emma", isGeorgian: false, bio: "ბარისტა კაფეში", look: {"skin": "#F6D5BE", "hair": "#D9A441", "style": "long", "shirt": "#2F9E77", "bg": "#162E26"} },
  james: { id: 'james', name: "James", isGeorgian: false, bio: "სასტუმროს მიმღები", look: {"skin": "#8D5A3B", "hair": "#1A1210", "style": "short", "shirt": "#24476E", "bg": "#1A2533"} },
  kate: { id: 'kate', name: "Kate", isGeorgian: false, bio: "გამვლელი ლონდონის ქუჩაზე", look: {"skin": "#F3CFB3", "hair": "#A0522D", "style": "bun", "shirt": "#E67E22", "bg": "#33200F"} },
  david: { id: 'david', name: "David", isGeorgian: false, bio: "მიმტანი რესტორანში", look: {"skin": "#C68B5E", "hair": "#1A1210", "style": "beard", "shirt": "#E9EDF2", "bg": "#262A30"} },
  lucy: { id: 'lucy', name: "Lucy", isGeorgian: false, bio: "გამყიდველი მაღაზიაში", look: {"skin": "#6E4630", "hair": "#1A1210", "style": "curly", "shirt": "#E84393", "bg": "#3A1A2C"} },
  anna: { id: 'anna', name: "Anna", isGeorgian: false, bio: "აეროპორტის თანამშრომელი", look: {"skin": "#F2D2BC", "hair": "#2B1B12", "style": "long", "shirt": "#2D6CDF", "bg": "#172540"} },
  brown: { id: 'brown', name: "Dr Brown", isGeorgian: false, bio: "ექიმი კლინიკაში", look: {"skin": "#E9C3A2", "hair": "#B9BEC6", "style": "short", "shirt": "#E8F1F8", "bg": "#1E2B33"} },
};

export const SECTIONS: Section[] = [
  { id: 's1', position: 1, cefr: 'A1', name: "დამწყები", description: "პირველი ნაბიჯები: გაცნობა, კაფე, სასტუმრო და ქალაქში გადაადგილება.", locked: false },
  { id: 's2', position: 2, cefr: 'A2', name: "საბაზისო", description: "მოგზაურობის რეალური სიტუაციები: რესტორანი, მაღაზია, აეროპორტი, ექიმი.", locked: false },
  { id: 's3', position: 3, cefr: 'B1', name: "საშუალო", description: "თავისუფალი საუბარი, სამსახური და ტელეფონით კომუნიკაცია.", locked: true, comingSoon: [{ en: "Small talk", ka: "მცირე საუბარი" }, { en: "Job interview", ka: "გასაუბრება სამსახურში" }, { en: "Phone calls", ka: "სატელეფონო საუბარი" }, { en: "Renting a flat", ka: "ბინის ქირაობა" }] },
  { id: 's4', position: 4, cefr: 'B2', name: "საშუალოზე მაღალი", description: "სამუშაო შეხვედრები, აზრის გამოხატვა და მოლაპარაკება.", locked: true, comingSoon: [{ en: "Work meetings", ka: "სამუშაო შეხვედრები" }, { en: "Giving opinions", ka: "აზრის გამოთქმა" }, { en: "The news", ka: "სიახლეები" }, { en: "Negotiating", ka: "მოლაპარაკება" }] },
];

export const UNITS: Unit[] = [
  {
    id: 'u1', sectionId: 's1', position: 1,
    en: "Meeting people", ka: "გაცნობა და მისალმება",
    host: 'nino', partner: 'tom',
    scene: "ნინო ენების გაცვლის საღამოზეა და ტომს ეცნობა.",
    tip: "ინგლისურ წინადადებას ყოველთვის სჭირდება ზმნა. „ვარ“ = I am, „ხარ / ხართ“ = you are. ქართულში ხშირად ზმნას ვტოვებთ, ინგლისურში კი არასდროს: სწორია „I am fine“ და არა „I fine“.",
    shortTip: "ინგლისურში ზმნა არ გამოიტოვება: I am fine.",
    grammar: { title: "ზმნა to be: am / is / are", explanation: "I am (მე ვარ), you are (შენ ხარ / თქვენ ხართ), he / she is (ის არის). ქართულად ხშირად ვამბობთ უბრალოდ „კარგად“, ინგლისურად კი ზმნა აუცილებელია.", examples: [{ en: "I am Nino.", ka: "მე ნინო ვარ." }, { en: "You are my friend.", ka: "შენ ჩემი მეგობარი ხარ." }, { en: "She is from Tbilisi.", ka: "ის თბილისიდანაა." }] },
    vocab: [
      { id: 'u1.v1', en: "hello", ka: "გამარჯობა", image: 'waving', phonetic: "/həˈloʊ/" },
      { id: 'u1.v2', en: "thank you", ka: "გმადლობთ", image: 'folded', phonetic: "/ˈθæŋk juː/" },
      { id: 'u1.v3', en: "please", ka: "გთხოვთ", image: 'palms', phonetic: "/pliːz/" },
      { id: 'u1.v4', en: "goodbye", ka: "ნახვამდის", image: 'walking', phonetic: "/ɡʊdˈbaɪ/" },
      { id: 'u1.v5', en: "name", ka: "სახელი", image: 'label', phonetic: "/neɪm/" },
      { id: 'u1.v6', en: "friend", ka: "მეგობარი", image: 'handshake', phonetic: "/frɛnd/" },
    ],
    phrases: [
      { id: 'u1.p1', en: "Hello, my name is Nino.", ka: "გამარჯობა, მე ნინო მქვია." },
      { id: 'u1.p2', en: "Nice to meet you.", ka: "სასიამოვნოა თქვენი გაცნობა." },
      { id: 'u1.p3', en: "How are you?", ka: "როგორ ხართ?" },
      { id: 'u1.p4', en: "I am fine, thank you.", ka: "კარგად ვარ, გმადლობთ." },
      { id: 'u1.p5', en: "Where are you from?", ka: "საიდან ხართ?" },
      { id: 'u1.p6', en: "I am from Georgia.", ka: "მე საქართველოდან ვარ." },
      { id: 'u1.p7', en: "What is your name?", ka: "რა გქვიათ?" },
      { id: 'u1.p8', en: "See you tomorrow.", ka: "ხვალამდე." },
    ],
    dialog: [
      { id: 'u1.d1', speaker: 'tom', en: "Hi! I'm Tom. What is your name?", ka: "გამარჯობა! მე ტომი ვარ. რა გქვია?" },
      { id: 'u1.d2', speaker: 'nino', en: "Hello, my name is Nino. Nice to meet you.", ka: "გამარჯობა, მე ნინო მქვია. სასიამოვნოა შენი გაცნობა." },
      { id: 'u1.d3', speaker: 'tom', en: "Nice to meet you too. Where are you from?", ka: "მეც სასიამოვნოა. საიდან ხარ?" },
      { id: 'u1.d4', speaker: 'nino', en: "I am from Georgia. And you?", ka: "საქართველოდან ვარ. შენ?" },
      { id: 'u1.d5', speaker: 'tom', en: "I am from London. How are you today?", ka: "ლონდონიდან. როგორ ხარ დღეს?" },
      { id: 'u1.d6', speaker: 'nino', en: "I am fine, thank you. See you tomorrow!", ka: "კარგად ვარ, გმადლობ. ხვალამდე!" },
    ],
    mistakes: [
      { id: 'u1.m1', wrong: "I fine.", correct: "I am fine.", note: "ზმნა am არ გამოტოვო." },
      { id: 'u1.m2', wrong: "My name Nino.", correct: "My name is Nino.", note: "name-ის შემდეგ საჭიროა is." },
    ],
    soundTip: "th სიტყვაში thank you ქართული „თ“ არ არის: ენის წვერი ოდნავ კბილებს შორის მოათავსე და ჰაერი ნაზად გაუშვი.",
    note: "you ნიშნავს „შენ“-საც და „თქვენ“-საც. თავაზიანობას ინგლისურში ტონი და სიტყვები please და thank you გამოხატავს.",
  },
  {
    id: 'u2', sectionId: 's1', position: 2,
    en: "At the café", ka: "კაფეში",
    host: 'giorgi', partner: 'emma',
    scene: "გიორგი ლონდონის კაფეში ყავას უკვეთავს. ბარისტა ემაა.",
    tip: "ქართულში არტიკლი არ გვაქვს. ინგლისურში ერთი საგნის წინ ვამბობთ a-ს: a coffee, a cake. თუ სიტყვა ხმოვანი ბგერით იწყება, ვამბობთ an-ს: an apple. სიტყვა please თხოვნას თავაზიანს ხდის.",
    shortTip: "ერთი საგნის წინ ვამბობთ a-ს: a coffee, a cake.",
    grammar: { title: "a / an: ერთი რაღაც", explanation: "ერთი, დასათვლელი საგნის წინ ვამბობთ a-ს. თუ სიტყვა ხმოვანი ბგერით იწყება, ვამბობთ an-ს. ქართულს არტიკლი არ აქვს, ამიტომ მისი დავიწყება ძალიან ხშირი შეცდომაა.", examples: [{ en: "a coffee", ka: "ერთი ყავა" }, { en: "an apple", ka: "ერთი ვაშლი" }, { en: "a glass of water", ka: "ერთი ჭიქა წყალი" }] },
    vocab: [
      { id: 'u2.v1', en: "coffee", ka: "ყავა", image: 'coffee', phonetic: "/ˈkɔː.fi/" },
      { id: 'u2.v2', en: "tea", ka: "ჩაი", image: 'tea', phonetic: "/tiː/" },
      { id: 'u2.v3', en: "water", ka: "წყალი", image: 'droplet', phonetic: "/ˈwɔː.tər/" },
      { id: 'u2.v4', en: "sugar", ka: "შაქარი", image: 'candy', phonetic: "/ˈʃʊɡ.ər/" },
      { id: 'u2.v5', en: "milk", ka: "რძე", image: 'milk', phonetic: "/mɪlk/" },
      { id: 'u2.v6', en: "cake", ka: "ნამცხვარი", image: 'cake', phonetic: "/keɪk/" },
    ],
    phrases: [
      { id: 'u2.p1', en: "A coffee, please.", ka: "ერთი ყავა, თუ შეიძლება." },
      { id: 'u2.p2', en: "Can I have a tea with milk?", ka: "შეიძლება ჩაი რძით?" },
      { id: 'u2.p3', en: "How much is it?", ka: "რა ღირს?" },
      { id: 'u2.p4', en: "I would like a glass of water.", ka: "ერთი ჭიქა წყალი მინდა." },
      { id: 'u2.p5', en: "Without sugar, please.", ka: "შაქრის გარეშე, თუ შეიძლება." },
      { id: 'u2.p6', en: "Can I pay by card?", ka: "შეიძლება ბარათით გადავიხადო?" },
      { id: 'u2.p7', en: "To go, please.", ka: "წასაღებად, თუ შეიძლება." },
      { id: 'u2.p8', en: "The cake is delicious.", ka: "ნამცხვარი გემრიელია." },
    ],
    dialog: [
      { id: 'u2.d1', speaker: 'emma', en: "Hi! What can I get you?", ka: "გამარჯობა! რას მიირთმევთ?" },
      { id: 'u2.d2', speaker: 'giorgi', en: "A coffee, please. Without sugar.", ka: "ერთი ყავა, თუ შეიძლება. შაქრის გარეშე." },
      { id: 'u2.d3', speaker: 'emma', en: "Sure. For here or to go?", ka: "რა თქმა უნდა. აქ დალევთ თუ წაიღებთ?" },
      { id: 'u2.d4', speaker: 'giorgi', en: "To go, please. How much is it?", ka: "წასაღებად, თუ შეიძლება. რა ღირს?" },
      { id: 'u2.d5', speaker: 'emma', en: "Three pounds fifty.", ka: "სამი ფუნტი და ორმოცდაათი პენსი." },
      { id: 'u2.d6', speaker: 'giorgi', en: "Can I pay by card?", ka: "შეიძლება ბარათით გადავიხადო?" },
    ],
    mistakes: [
      { id: 'u2.m1', wrong: "I want coffee.", correct: "I would like a coffee, please.", note: "I want უხეშად ჟღერს, I would like თავაზიანია." },
      { id: 'u2.m2', wrong: "Give me tea.", correct: "Can I have a tea, please?", note: "თხოვნა კითხვის ფორმით უფრო ბუნებრივია." },
    ],
    soundTip: "water ამერიკულად ჟღერს დაახლოებით „უოდერ“, ბრიტანულად „უოტა“. ორივე სწორია.",
    note: "ბრიტანეთის კაფეებში ხშირად გკითხავენ: For here or to go? ანუ აქ დალევთ თუ თან წაიღებთ.",
  },
  {
    id: 'u3', sectionId: 's1', position: 3,
    en: "Hotel check-in", ka: "სასტუმროში",
    host: 'tamar', partner: 'james',
    scene: "თამარი კონფერენციაზე ჩავიდა და სასტუმროში რეგისტრირდება.",
    tip: "Can I have…? ყველაზე მარტივი და თავაზიანი თხოვნაა სასტუმროში, კაფეში თუ მაღაზიაში. პასუხად ხშირად გაიგებთ: Sure! ან Of course!",
    shortTip: "Can I have…? თავაზიანი თხოვნაა.",
    grammar: { title: "Can I have…? თავაზიანი თხოვნა", explanation: "Can I have + საგანი? ასე ითხოვენ თითქმის ყველაფერს: გასაღებს, პირსახოცს, ანგარიშს. უფრო ოფიციალურად: Could I have…?", examples: [{ en: "Can I have another key?", ka: "შეიძლება კიდევ ერთი გასაღები?" }, { en: "Could I have a towel?", ka: "შეიძლება პირსახოცი?" }, { en: "Can I have the Wi-Fi password?", ka: "შეიძლება Wi-Fi-ს პაროლი?" }] },
    vocab: [
      { id: 'u3.v1', en: "room", ka: "ოთახი", image: 'bed', phonetic: "/ruːm/" },
      { id: 'u3.v2', en: "key", ka: "გასაღები", image: 'key', phonetic: "/kiː/" },
      { id: 'u3.v3', en: "reservation", ka: "ჯავშანი", image: 'clipboard', phonetic: "/ˌrɛz.ərˈveɪ.ʃən/" },
      { id: 'u3.v4', en: "night", ka: "ღამე", image: 'moon', phonetic: "/naɪt/" },
      { id: 'u3.v5', en: "breakfast", ka: "საუზმე", image: 'cooking', phonetic: "/ˈbrɛk.fəst/" },
      { id: 'u3.v6', en: "passport", ka: "პასპორტი", image: 'passport', phonetic: "/ˈpæs.pɔːrt/" },
    ],
    phrases: [
      { id: 'u3.p1', en: "I have a reservation.", ka: "ოთახი დაჯავშნილი მაქვს." },
      { id: 'u3.p2', en: "For three nights.", ka: "სამი ღამით." },
      { id: 'u3.p3', en: "What time is breakfast?", ka: "რომელ საათზეა საუზმე?" },
      { id: 'u3.p4', en: "Here is my passport.", ka: "აი, ჩემი პასპორტი." },
      { id: 'u3.p5', en: "Is the Wi-Fi free?", ka: "Wi-Fi უფასოა?" },
      { id: 'u3.p6', en: "The room is too cold.", ka: "ოთახში ძალიან ცივა." },
      { id: 'u3.p7', en: "Can I have another key?", ka: "შეიძლება კიდევ ერთი გასაღები?" },
      { id: 'u3.p8', en: "What time is check-out?", ka: "რომელ საათზეა ნომრის დატოვება?" },
    ],
    dialog: [
      { id: 'u3.d1', speaker: 'james', en: "Good evening! How can I help you?", ka: "საღამო მშვიდობისა! რით შემიძლია დაგეხმაროთ?" },
      { id: 'u3.d2', speaker: 'tamar', en: "Hello, I have a reservation.", ka: "გამარჯობა, ოთახი დაჯავშნილი მაქვს." },
      { id: 'u3.d3', speaker: 'james', en: "What is your name, please?", ka: "თქვენი სახელი, თუ შეიძლება?" },
      { id: 'u3.d4', speaker: 'tamar', en: "Tamar Beridze. For three nights.", ka: "თამარ ბერიძე. სამი ღამით." },
      { id: 'u3.d5', speaker: 'james', en: "Here is your key. Room 305.", ka: "აი, თქვენი გასაღები. ოთახი 305." },
      { id: 'u3.d6', speaker: 'tamar', en: "Thank you. What time is breakfast?", ka: "გმადლობთ. რომელ საათზეა საუზმე?" },
    ],
    mistakes: [
      { id: 'u3.m1', wrong: "I have reservation.", correct: "I have a reservation.", note: "reservation-ის წინ a სჭირდება." },
      { id: 'u3.m2', wrong: "For three night.", correct: "For three nights.", note: "ერთზე მეტის შემთხვევაში სიტყვას -s ემატება." },
    ],
    soundTip: "room გამოითქმის გრძელი „უუ“-თი: „რუუმ“. key კი გრძელი „ი“-თი: „ქიი“.",
    note: "ოთახის ნომერს ციფრებად ამბობენ: Room 305 ჟღერს როგორც „three-oh-five“.",
  },
  {
    id: 'u4', sectionId: 's1', position: 4,
    en: "Getting around", ka: "ქალაქში გადაადგილება",
    host: 'luka', partner: 'kate',
    scene: "ლუკა პირველად არის ლონდონში და მეტროს სადგურს ეძებს.",
    tip: "კითხვა „სად არის…?“ ინგლისურად იწყება Where is…-ით. კითხვაში ზმნა is ქვემდებარის წინ გადადის: The station is near → Where is the station?",
    shortTip: "კითხვაში is წინ გადადის: Where is the station?",
    grammar: { title: "კითხვა Where is…?", explanation: "კითხვაში is ქვემდებარის წინ გადადის. მრავლობითში is-ის ნაცვლად ვამბობთ are-ს: Where are the taxis?", examples: [{ en: "The station is near.", ka: "სადგური ახლოსაა." }, { en: "Where is the station?", ka: "სად არის სადგური?" }, { en: "Where are the toilets?", ka: "სად არის ტუალეტები?" }] },
    vocab: [
      { id: 'u4.v1', en: "street", ka: "ქუჩა", image: 'motorway', phonetic: "/striːt/" },
      { id: 'u4.v2', en: "station", ka: "სადგური", image: 'station', phonetic: "/ˈsteɪ.ʃən/" },
      { id: 'u4.v3', en: "taxi", ka: "ტაქსი", image: 'taxi', phonetic: "/ˈtæk.si/" },
      { id: 'u4.v4', en: "left", ka: "მარცხნივ", image: 'left', phonetic: "/lɛft/" },
      { id: 'u4.v5', en: "right", ka: "მარჯვნივ", image: 'right', phonetic: "/raɪt/" },
      { id: 'u4.v6', en: "ticket", ka: "ბილეთი", image: 'ticket', phonetic: "/ˈtɪk.ɪt/" },
    ],
    phrases: [
      { id: 'u4.p1', en: "Where is the metro station?", ka: "სად არის მეტროს სადგური?" },
      { id: 'u4.p2', en: "Turn left at the corner.", ka: "კუთხეში მოუხვიეთ მარცხნივ." },
      { id: 'u4.p3', en: "Go straight ahead.", ka: "პირდაპირ იარეთ." },
      { id: 'u4.p4', en: "How far is it?", ka: "რამდენად შორსაა?" },
      { id: 'u4.p5', en: "One ticket to Batumi, please.", ka: "ერთი ბილეთი ბათუმამდე, თუ შეიძლება." },
      { id: 'u4.p6', en: "Can you call a taxi?", ka: "შეგიძლიათ ტაქსი გამოიძახოთ?" },
      { id: 'u4.p7', en: "Stop here, please.", ka: "აქ გამიჩერეთ, თუ შეიძლება." },
      { id: 'u4.p8', en: "I am lost.", ka: "გზა ამებნა." },
    ],
    dialog: [
      { id: 'u4.d1', speaker: 'luka', en: "Excuse me, where is the metro station?", ka: "ბოდიში, სად არის მეტროს სადგური?" },
      { id: 'u4.d2', speaker: 'kate', en: "Go straight ahead and turn left at the corner.", ka: "პირდაპირ იარეთ და კუთხეში მოუხვიეთ მარცხნივ." },
      { id: 'u4.d3', speaker: 'luka', en: "How far is it?", ka: "რამდენად შორსაა?" },
      { id: 'u4.d4', speaker: 'kate', en: "About five minutes on foot.", ka: "ფეხით დაახლოებით ხუთი წუთია." },
      { id: 'u4.d5', speaker: 'luka', en: "Thank you very much!", ka: "დიდი მადლობა!" },
      { id: 'u4.d6', speaker: 'kate', en: "You're welcome. Have a nice day!", ka: "არაფრის. კარგ დღეს გისურვებთ!" },
    ],
    mistakes: [
      { id: 'u4.m1', wrong: "Where the station is?", correct: "Where is the station?", note: "კითხვაში is წინ მოდის." },
      { id: 'u4.m2', wrong: "Where is metro?", correct: "Where is the metro?", note: "კონკრეტული ადგილის წინ ვამბობთ the-ს." },
    ],
    soundTip: "left და right: l-ის დროს ენის წვერი ზემო კბილებს ეხება, r-ის დროს ენა არაფერს ეხება და არ ცახცახებს.",
    note: "ლონდონში მეტროს the Underground ან the Tube ჰქვია, ნიუ-იორკში კი the subway.",
  },
  {
    id: 'u5', sectionId: 's2', position: 1,
    en: "At the restaurant", ka: "რესტორანში",
    host: 'nino', partner: 'david',
    scene: "ნინო და გიორგი რესტორანში ვახშმობენ. მიმტანი დევიდია.",
    tip: "შეკვეთისას ამბობენ I'll have… (= I will have) ან I'd like… (= I would like). ორივე გაცილებით თავაზიანად ჟღერს, ვიდრე I want.",
    shortTip: "შეკვეთისას ამბობენ I'll have… ან I'd like…",
    grammar: { title: "I'll have… / I'd like…: შეკვეთა", explanation: "I'll = I will, I'd = I would. რესტორანში I want-ის ნაცვლად სწორედ ამ ფორმებს იყენებენ.", examples: [{ en: "I'll have the soup.", ka: "სუპს ავიღებ." }, { en: "I'd like a salad.", ka: "სალათი მინდა." }, { en: "We'd like some water.", ka: "ცოტა წყალი გვინდა." }] },
    vocab: [
      { id: 'u5.v1', en: "menu", ka: "მენიუ", image: 'book', phonetic: "/ˈmɛn.juː/" },
      { id: 'u5.v2', en: "table", ka: "მაგიდა", image: 'plate', phonetic: "/ˈteɪ.bəl/" },
      { id: 'u5.v3', en: "waiter", ka: "მიმტანი", image: 'tuxedo', phonetic: "/ˈweɪ.tər/" },
      { id: 'u5.v4', en: "bill", ka: "ანგარიში", image: 'receipt', phonetic: "/bɪl/" },
      { id: 'u5.v5', en: "soup", ka: "სუპი", image: 'pot', phonetic: "/suːp/" },
      { id: 'u5.v6', en: "fish", ka: "თევზი", image: 'fish', phonetic: "/fɪʃ/" },
    ],
    phrases: [
      { id: 'u5.p1', en: "A table for two, please.", ka: "მაგიდა ორისთვის, თუ შეიძლება." },
      { id: 'u5.p2', en: "Can we see the menu?", ka: "შეიძლება მენიუ ვნახოთ?" },
      { id: 'u5.p3', en: "What do you recommend?", ka: "რას გვირჩევთ?" },
      { id: 'u5.p4', en: "I am allergic to fish.", ka: "თევზზე ალერგია მაქვს." },
      { id: 'u5.p5', en: "I will have the soup.", ka: "სუპს ავიღებ." },
      { id: 'u5.p6', en: "Could we have the bill, please?", ka: "ანგარიში მოგვიტანეთ, თუ შეიძლება." },
      { id: 'u5.p7', en: "Is service included?", ka: "მომსახურება ფასში შედის?" },
      { id: 'u5.p8', en: "Everything was delicious.", ka: "ყველაფერი გემრიელი იყო." },
    ],
    dialog: [
      { id: 'u5.d1', speaker: 'david', en: "Good evening. A table for two?", ka: "საღამო მშვიდობისა. მაგიდა ორისთვის?" },
      { id: 'u5.d2', speaker: 'nino', en: "Yes, please. Can we see the menu?", ka: "დიახ. შეიძლება მენიუ ვნახოთ?" },
      { id: 'u5.d3', speaker: 'david', en: "Of course. Are you ready to order?", ka: "რა თქმა უნდა. მზად ხართ შესაკვეთად?" },
      { id: 'u5.d4', speaker: 'nino', en: "I will have the soup. I am allergic to fish.", ka: "სუპს ავიღებ. თევზზე ალერგია მაქვს." },
      { id: 'u5.d5', speaker: 'david', en: "No problem. Anything to drink?", ka: "პრობლემა არაა. დასალევად რას ინებებთ?" },
      { id: 'u5.d6', speaker: 'nino', en: "Just water, please.", ka: "მხოლოდ წყალი, თუ შეიძლება." },
    ],
    mistakes: [
      { id: 'u5.m1', wrong: "Bring me the bill.", correct: "Could we have the bill, please?", note: "ბრძანებითი ფორმა უხეშად ჟღერს." },
      { id: 'u5.m2', wrong: "I am allergy to fish.", correct: "I am allergic to fish.", note: "allergy არსებითი სახელია, allergic ზედსართავი." },
    ],
    soundTip: "bill გამოითქმის მოკლე „ი“-თი: „ბილ“. გრძელი „ი“ (beel) სხვა სიტყვად ჟღერს.",
    note: "ანგარიშის წინ იკითხე Is service included? ხშირად ჩაის ფული (tip) უკვე შედის ფასში.",
  },
  {
    id: 'u6', sectionId: 's2', position: 2,
    en: "Shopping", ka: "საყიდლებზე",
    host: 'mariam', partner: 'lucy',
    scene: "მარიამი ახალ პერანგს ყიდულობს. გამყიდველი ლუსია.",
    tip: "too და very სხვადასხვაა: very expensive = ძალიან ძვირი, too expensive = ზედმეტად ძვირი (ანუ არ ვყიდულობ). შედარებისას: small → smaller, big → bigger.",
    shortTip: "too expensive ნიშნავს ზედმეტად ძვირს.",
    grammar: { title: "too და very; smaller, bigger", explanation: "very = ძალიან, too = ზედმეტად (ანუ არ გამომადგება). შედარებისას მოკლე სიტყვებს ემატება -er: small → smaller, cheap → cheaper. გრძელ სიტყვებთან: more expensive.", examples: [{ en: "It is very nice.", ka: "ძალიან ლამაზია." }, { en: "It is too big.", ka: "ზედმეტად დიდია." }, { en: "Do you have a cheaper one?", ka: "უფრო იაფი გაქვთ?" }] },
    vocab: [
      { id: 'u6.v1', en: "size", ka: "ზომა", image: 'ruler', phonetic: "/saɪz/" },
      { id: 'u6.v2', en: "price", ka: "ფასი", image: 'label', phonetic: "/praɪs/" },
      { id: 'u6.v3', en: "cheap", ka: "იაფი", image: 'coin', phonetic: "/tʃiːp/" },
      { id: 'u6.v4', en: "expensive", ka: "ძვირი", image: 'gem', phonetic: "/ɪkˈspɛn.sɪv/" },
      { id: 'u6.v5', en: "shirt", ka: "პერანგი", image: 'shirt', phonetic: "/ʃɜːrt/" },
      { id: 'u6.v6', en: "shoes", ka: "ფეხსაცმელი", image: 'shoe', phonetic: "/ʃuːz/" },
    ],
    phrases: [
      { id: 'u6.p1', en: "How much does this cost?", ka: "ეს რა ღირს?" },
      { id: 'u6.p2', en: "Do you have a smaller size?", ka: "უფრო პატარა ზომა გაქვთ?" },
      { id: 'u6.p3', en: "Can I try it on?", ka: "შეიძლება მოვიზომო?" },
      { id: 'u6.p4', en: "It is too expensive.", ka: "ზედმეტად ძვირია." },
      { id: 'u6.p5', en: "I am just looking.", ka: "უბრალოდ ვათვალიერებ." },
      { id: 'u6.p6', en: "Where is the fitting room?", ka: "სად არის გასახდელი?" },
      { id: 'u6.p7', en: "I will take it.", ka: "ამას ავიღებ." },
      { id: 'u6.p8', en: "Do you have it in black?", ka: "შავი ფერის გაქვთ?" },
    ],
    dialog: [
      { id: 'u6.d1', speaker: 'lucy', en: "Hi! Can I help you?", ka: "გამარჯობა! შემიძლია დაგეხმაროთ?" },
      { id: 'u6.d2', speaker: 'mariam', en: "I am just looking, thanks.", ka: "უბრალოდ ვათვალიერებ, მადლობა." },
      { id: 'u6.d3', speaker: 'lucy', en: "Sure. Let me know if you need anything.", ka: "კარგი. თუ რამე დაგჭირდებათ, მითხარით." },
      { id: 'u6.d4', speaker: 'mariam', en: "Do you have a smaller size?", ka: "უფრო პატარა ზომა გაქვთ?" },
      { id: 'u6.d5', speaker: 'lucy', en: "Yes, here you are. The fitting room is over there.", ka: "დიახ, ინებეთ. გასახდელი იქაა." },
      { id: 'u6.d6', speaker: 'mariam', en: "Thank you. I will take it!", ka: "გმადლობთ. ამას ავიღებ!" },
    ],
    mistakes: [
      { id: 'u6.m1', wrong: "It is more cheap.", correct: "It is cheaper.", note: "მოკლე ზედსართავს -er ემატება." },
      { id: 'u6.m2', wrong: "How much it costs?", correct: "How much does it cost?", note: "კითხვაში საჭიროა does." },
    ],
    soundTip: "shirt და shoes იწყება ბგერით sh, რომელიც ქართულ „შ“-ს ჰგავს.",
    note: "ტანსაცმლის ზომები ქვეყნების მიხედვით განსხვავდება. მოზომვამდე იკითხე: Can I try it on?",
  },
  {
    id: 'u7', sectionId: 's2', position: 3,
    en: "At the airport", ka: "აეროპორტში",
    host: 'giorgi', partner: 'anna',
    scene: "გიორგი სახლში ბრუნდება და აეროპორტში რეგისტრაციას გადის.",
    tip: "აეროპორტში ხშირად გაიგებთ ფორმას am / is / are + ზმნა-ing: Boarding is starting now, the plane is leaving. ეს ნიშნავს, რომ მოქმედება ახლა ხდება.",
    shortTip: "am / is / are + -ing ნიშნავს ახლა მიმდინარე მოქმედებას.",
    grammar: { title: "am / is / are + -ing: ახლა მიმდინარე", explanation: "როცა მოქმედება ახლა ხდება, ვამბობთ am / is / are + ზმნა-ing: The plane is leaving. აეროპორტის განცხადებებში ამ ფორმას ხშირად გაიგებ.", examples: [{ en: "Boarding is starting now.", ka: "ჩასხდომა ახლა იწყება." }, { en: "I am waiting at gate twelve.", ka: "მეთორმეტე გასასვლელთან ველოდები." }, { en: "We are flying to Tbilisi.", ka: "თბილისში მივფრინავთ." }] },
    vocab: [
      { id: 'u7.v1', en: "flight", ka: "რეისი", image: 'airplane', phonetic: "/flaɪt/" },
      { id: 'u7.v2', en: "gate", ka: "გასასვლელი", image: 'door', phonetic: "/ɡeɪt/" },
      { id: 'u7.v3', en: "luggage", ka: "ბარგი", image: 'luggage', phonetic: "/ˈlʌɡ.ɪdʒ/" },
      { id: 'u7.v4', en: "delay", ka: "დაგვიანება", image: 'alarm', phonetic: "/dɪˈleɪ/" },
      { id: 'u7.v5', en: "boarding pass", ka: "ჩასხდომის ბარათი", image: 'tickets', phonetic: "/ˈbɔːr.dɪŋ pæs/" },
      { id: 'u7.v6', en: "seat", ka: "ადგილი", image: 'seat', phonetic: "/siːt/" },
    ],
    phrases: [
      { id: 'u7.p1', en: "Where is gate twelve?", ka: "სად არის მეთორმეტე გასასვლელი?" },
      { id: 'u7.p2', en: "My flight is delayed.", ka: "ჩემი რეისი იგვიანებს." },
      { id: 'u7.p3', en: "I have one bag to check in.", ka: "ერთი ჩანთა მაქვს ჩასაბარებელი." },
      { id: 'u7.p4', en: "Can I have a window seat?", ka: "შეიძლება ფანჯარასთან ადგილი?" },
      { id: 'u7.p5', en: "My luggage is lost.", ka: "ჩემი ბარგი დაიკარგა." },
      { id: 'u7.p6', en: "When does boarding start?", ka: "როდის იწყება ჩასხდომა?" },
      { id: 'u7.p7', en: "I am here on holiday.", ka: "აქ დასასვენებლად ვარ." },
      { id: 'u7.p8', en: "How long is the flight?", ka: "რამდენ ხანს გრძელდება ფრენა?" },
    ],
    dialog: [
      { id: 'u7.d1', speaker: 'anna', en: "Good morning. Your passport, please.", ka: "დილა მშვიდობისა. თქვენი პასპორტი, თუ შეიძლება." },
      { id: 'u7.d2', speaker: 'giorgi', en: "Here you are. I have one bag to check in.", ka: "ინებეთ. ერთი ჩანთა მაქვს ჩასაბარებელი." },
      { id: 'u7.d3', speaker: 'anna', en: "Would you like a window seat or an aisle seat?", ka: "ფანჯარასთან ადგილი გნებავთ თუ გასასვლელთან?" },
      { id: 'u7.d4', speaker: 'giorgi', en: "A window seat, please. When does boarding start?", ka: "ფანჯარასთან, თუ შეიძლება. როდის იწყება ჩასხდომა?" },
      { id: 'u7.d5', speaker: 'anna', en: "At ten thirty. Gate twelve.", ka: "10:30-ზე. მეთორმეტე გასასვლელი." },
      { id: 'u7.d6', speaker: 'giorgi', en: "Thank you. Is the flight on time?", ka: "გმადლობთ. რეისი დროზეა?" },
    ],
    mistakes: [
      { id: 'u7.m1', wrong: "My flight delayed.", correct: "My flight is delayed.", note: "is აუცილებელია." },
      { id: 'u7.m2', wrong: "I am go to London.", correct: "I am going to London.", note: "am-ის შემდეგ ზმნას ემატება -ing." },
    ],
    soundTip: "luggage გამოითქმის დაახლოებით „ლაგიჯ“: ბოლოში ჟღერს „ჯ“ და არა „გე“.",
    note: "check in ნიშნავს რეგისტრაციას და ბარგის ჩაბარებას, boarding კი თვითმფრინავში ჩასხდომას.",
  },
  {
    id: 'u8', sectionId: 's2', position: 4,
    en: "Doctor & pharmacy", ka: "ექიმთან და აფთიაქში",
    host: 'tamar', partner: 'brown',
    scene: "თამარი მოგზაურობისას შეუძლოდ გახდა და ექიმთან მივიდა.",
    tip: "ქართულად ვამბობთ „თავი მტკივა“, ინგლისურად კი ტკივილი „გვაქვს“: I have a headache, I have a fever. ზოგადად ტკივილზე: It hurts here.",
    shortTip: "ინგლისურად ტკივილი „გვაქვს“: I have a headache.",
    grammar: { title: "I have a…: ტკივილი და სიმპტომები", explanation: "ქართულად ვამბობთ „თავი მტკივა“, ინგლისურად კი ტკივილი „გვაქვს“: I have a headache. კონკრეტულ ადგილზე: It hurts here ან My back hurts.", examples: [{ en: "I have a headache.", ka: "თავი მტკივა." }, { en: "I have a cold.", ka: "გაციებული ვარ." }, { en: "My back hurts.", ka: "ზურგი მტკივა." }] },
    vocab: [
      { id: 'u8.v1', en: "headache", ka: "თავის ტკივილი", image: 'bandage', phonetic: "/ˈhɛd.eɪk/" },
      { id: 'u8.v2', en: "fever", ka: "სიცხე", image: 'thermo', phonetic: "/ˈfiː.vər/" },
      { id: 'u8.v3', en: "medicine", ka: "წამალი", image: 'pill', phonetic: "/ˈmɛd.ɪ.sən/" },
      { id: 'u8.v4', en: "pharmacy", ka: "აფთიაქი", image: 'medical', phonetic: "/ˈfɑːr.mə.si/" },
      { id: 'u8.v5', en: "doctor", ka: "ექიმი", image: 'stetho', phonetic: "/ˈdɑːk.tər/" },
      { id: 'u8.v6', en: "pain", ka: "ტკივილი", image: 'persevere', phonetic: "/peɪn/" },
    ],
    phrases: [
      { id: 'u8.p1', en: "I need a doctor.", ka: "ექიმი მჭირდება." },
      { id: 'u8.p2', en: "I have a headache.", ka: "თავი მტკივა." },
      { id: 'u8.p3', en: "I have a fever.", ka: "სიცხე მაქვს." },
      { id: 'u8.p4', en: "Where is the nearest pharmacy?", ka: "სად არის უახლოესი აფთიაქი?" },
      { id: 'u8.p5', en: "How often should I take this?", ka: "რამდენად ხშირად უნდა მივიღო ეს?" },
      { id: 'u8.p6', en: "It hurts here.", ka: "აქ მტკივა." },
      { id: 'u8.p7', en: "Do I need a prescription?", ka: "რეცეპტი მჭირდება?" },
      { id: 'u8.p8', en: "I feel much better.", ka: "ბევრად უკეთ ვგრძნობ თავს." },
    ],
    dialog: [
      { id: 'u8.d1', speaker: 'brown', en: "Hello. What seems to be the problem?", ka: "გამარჯობა. რა გაწუხებთ?" },
      { id: 'u8.d2', speaker: 'tamar', en: "I have a headache and a fever.", ka: "თავი მტკივა და სიცხე მაქვს." },
      { id: 'u8.d3', speaker: 'brown', en: "How long have you had it?", ka: "რამდენი ხანია, რაც ასე ხართ?" },
      { id: 'u8.d4', speaker: 'tamar', en: "Since yesterday.", ka: "გუშინდლიდან." },
      { id: 'u8.d5', speaker: 'brown', en: "Take this medicine twice a day.", ka: "ეს წამალი დღეში ორჯერ მიიღეთ." },
      { id: 'u8.d6', speaker: 'tamar', en: "Thank you. Do I need a prescription?", ka: "გმადლობთ. რეცეპტი მჭირდება?" },
    ],
    mistakes: [
      { id: 'u8.m1', wrong: "My head is hurt.", correct: "My head hurts.", note: "hurts თავად ზმნაა, is არ სჭირდება." },
      { id: 'u8.m2', wrong: "I have temperature.", correct: "I have a fever.", note: "სიცხეზე ამბობენ a fever ან a temperature." },
    ],
    soundTip: "headache-ში ch იკითხება როგორც „კ“: „ჰედეიკ“.",
    note: "საგანგებო ნომერი ევროპის ქვეყნებში 112-ია, აშშ-ში 911, დიდ ბრიტანეთში 999 (112-იც მუშაობს).",
  },
];

/** Georgian word (or two-word phrase) -> English hint shown when the learner taps it. */
export const GLOSSARY: Record<string, string> = {
  "გამარჯობა": "hello",
  "მე": "I / me",
  "ნინო": "Nino",
  "მქვია": "my name is",
  "სასიამოვნოა": "nice (it is nice)",
  "თქვენი": "your",
  "გაცნობა": "to meet (you)",
  "როგორ": "how",
  "ხართ": "are (you)",
  "კარგად": "well / fine",
  "ვარ": "(I) am",
  "გმადლობთ": "thank you",
  "საიდან": "where … from",
  "საქართველოდან": "from Georgia",
  "რა": "what",
  "გქვიათ": "is your name",
  "ხვალამდე": "see you tomorrow",
  "ერთი": "one / a",
  "ყავა": "coffee",
  "თუ შეიძლება": "please",
  "შეიძლება": "can I…? / may I…?",
  "ჩაი": "tea",
  "რძით": "with milk",
  "ღირს": "cost(s)",
  "ჭიქა": "glass",
  "წყალი": "water",
  "მინდა": "I would like",
  "შაქრის": "sugar",
  "გარეშე": "without",
  "ბარათით": "by card",
  "გადავიხადო": "(I) pay",
  "წასაღებად": "to go (takeaway)",
  "ნამცხვარი": "cake",
  "გემრიელია": "is delicious",
  "ოთახი": "room",
  "დაჯავშნილი": "reserved",
  "მაქვს": "I have",
  "სამი": "three",
  "ღამით": "nights (for … nights)",
  "რომელ საათზეა": "what time is",
  "საუზმე": "breakfast",
  "აი": "here is",
  "ჩემი": "my",
  "პასპორტი": "passport",
  "Wi-Fi": "Wi-Fi",
  "უფასოა": "is free",
  "ოთახში": "in the room / the room",
  "ძალიან": "very / too",
  "ცივა": "is cold",
  "კიდევ": "another / more",
  "გასაღები": "key",
  "ნომრის დატოვება": "check-out",
  "სად": "where",
  "არის": "is",
  "მეტროს": "metro",
  "სადგური": "station",
  "კუთხეში": "at the corner",
  "მოუხვიეთ": "turn",
  "მარცხნივ": "left",
  "პირდაპირ": "straight ahead",
  "იარეთ": "go",
  "რამდენად": "how",
  "შორსაა": "far is it",
  "ბილეთი": "ticket",
  "ბათუმამდე": "to Batumi",
  "შეგიძლიათ": "can you",
  "ტაქსი": "taxi",
  "გამოიძახოთ": "call",
  "აქ": "here",
  "გამიჩერეთ": "stop (for me)",
  "გზა ამებნა": "I am lost",
  "მაგიდა": "table",
  "ორისთვის": "for two",
  "მენიუ": "menu",
  "ვნახოთ": "(we) see",
  "რას": "what",
  "გვირჩევთ": "do you recommend",
  "თევზზე": "to fish",
  "ალერგია": "allergic (allergy)",
  "სუპს": "the soup",
  "ავიღებ": "I will have / I'll take",
  "ანგარიში": "the bill",
  "მოგვიტანეთ": "bring us",
  "მომსახურება": "service",
  "ფასში": "in the price",
  "შედის": "is included",
  "ყველაფერი": "everything",
  "გემრიელი": "delicious",
  "იყო": "was",
  "ეს": "this",
  "უფრო": "more / -er",
  "პატარა": "small",
  "ზომა": "size",
  "გაქვთ": "do you have",
  "მოვიზომო": "try it on",
  "ზედმეტად": "too",
  "ძვირია": "is expensive",
  "უბრალოდ": "just",
  "ვათვალიერებ": "I am looking",
  "გასახდელი": "fitting room",
  "ამას": "this (one)",
  "შავი": "black",
  "ფერის": "(in) colour",
  "მეთორმეტე": "twelve (twelfth)",
  "გასასვლელი": "gate",
  "რეისი": "flight",
  "იგვიანებს": "is delayed",
  "ჩანთა": "bag",
  "ჩასაბარებელი": "to check in",
  "ფანჯარასთან": "window (by the window)",
  "ადგილი": "seat",
  "ბარგი": "luggage",
  "დაიკარგა": "is lost",
  "როდის": "when",
  "იწყება": "does … start",
  "ჩასხდომა": "boarding",
  "დასასვენებლად": "on holiday",
  "რამდენ ხანს": "how long",
  "გრძელდება": "is / lasts",
  "ფრენა": "the flight",
  "ექიმი": "a doctor",
  "მჭირდება": "I need",
  "თავი მტკივა": "I have a headache",
  "სიცხე": "a fever",
  "უახლოესი": "the nearest",
  "აფთიაქი": "pharmacy",
  "ხშირად": "often",
  "უნდა": "should",
  "მივიღო": "(I) take",
  "რეცეპტი": "a prescription",
  "ბევრად": "much",
  "უკეთ": "better",
  "ვგრძნობ თავს": "I feel",
  "მტკივა": "hurts",
  "ჩემი რეისი": "my flight",
};

export const LESSON_NAMES = ["ახალი სიტყვები", "პირველი ფრაზები", "მოსმენა და წერა", "დიალოგი"];
export const CHEERS = ["შენ შეძლებ!", "კიდევ ერთი ნახტომი!", "ძალიან კარგად მიდიხარ!", "გააგრძელე!"];
