/// <reference types="node" />
/**
 * Builds supabase/seed.sql from src/content so the database always mirrors the bundled course.
 * Run: npm run seed:generate
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CHARACTERS, GLOSSARY, PATH, SECTIONS, UNITS } from '../src/content';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const rows = (table: string, cols: string[], values: unknown[][], conflict = 'id') =>
  values.length
    ? `insert into public.${table} (${cols.join(', ')}) values\n` +
      values.map((r) => `  (${r.map(q).join(', ')})`).join(',\n') +
      `\non conflict (${conflict}) do update set ${cols.filter((c) => c !== conflict).map((c) => `${c} = excluded.${c}`).join(', ')};\n`
    : '';

const out: string[] = ['-- Generated by scripts/generate-seed.ts. Do not edit by hand.', 'begin;'];
out.push(rows('characters', ['id', 'name', 'is_georgian', 'bio_ka', 'look'],
  Object.values(CHARACTERS).map((c) => [c.id, c.name, c.isGeorgian, c.bio, c.look])));
out.push(rows('sections', ['id', 'position', 'cefr', 'name_ka', 'description_ka', 'is_locked'],
  SECTIONS.map((s) => [s.id, s.position, s.cefr, s.name, s.description, s.locked])));
out.push(rows('units', ['id', 'section_id', 'position', 'title_en', 'title_ka', 'tip_ka', 'short_tip_ka', 'scene_ka', 'host_id', 'partner_id', 'grammar', 'sound_tip_ka', 'note_ka'],
  UNITS.map((u) => [u.id, u.sectionId, u.position, u.en, u.ka, u.tip, u.shortTip, u.scene, u.host, u.partner, u.grammar, u.soundTip, u.note])));
out.push(rows('vocab_items', ['id', 'unit_id', 'position', 'en', 'ka', 'phonetic', 'image_key'],
  UNITS.flatMap((u) => u.vocab.map((v, i) => [v.id, u.id, i + 1, v.en, v.ka, v.phonetic ?? null, v.image]))));
out.push(rows('phrases', ['id', 'unit_id', 'position', 'en', 'ka'],
  UNITS.flatMap((u) => u.phrases.map((p, i) => [p.id, u.id, i + 1, p.en, p.ka]))));
out.push(rows('dialog_lines', ['id', 'unit_id', 'position', 'speaker_id', 'en', 'ka'],
  UNITS.flatMap((u) => u.dialog.map((d, i) => [d.id, u.id, i + 1, d.speaker, d.en, d.ka]))));
out.push(rows('common_mistakes', ['id', 'unit_id', 'position', 'wrong', 'correct', 'note_ka'],
  UNITS.flatMap((u) => u.mistakes.map((m, i) => [m.id, u.id, i + 1, m.wrong, m.correct, m.note]))));
out.push(rows('glossary', ['ka', 'en'], Object.entries(GLOSSARY), 'ka'));
out.push(rows('path_nodes', ['id', 'unit_id', 'position', 'seq', 'kind', 'lesson_number'],
  PATH.map((n) => [n.id, n.unitId, n.position, n.seq, n.kind, n.lessonNumber ?? null])));
out.push('commit;');

const file = join(__dirname, '..', 'supabase', 'seed.sql');
writeFileSync(file, out.join('\n'));
console.log(`Wrote ${file}`);
